[package]
name = "musmatic"
version = "0.1.0"
authors = ["adrq"]
edition = "2018"

#[lib]
#crate-type = ["dylib"]

[dependencies]
serde_json = "^1.*"
serde = "^1.*"
actix-web = "1.0.0-alpha.1"

[build-dependencies]
cmake = "*"
bindgen = "0.42.*"
