[package]
name = "musmatic"
version = "0.1.0"
authors = ["adrq"]
edition = "2018"

#[lib]
#crate-type = ["dylib"]

[dependencies]
serde_json = "^1.*"
serde = {version = "^1.*", features = ["derive"]}

[build-dependencies]
cmake = "*"
bindgen = "0.42.*"
